const crypto = require("node:crypto");
const { Pool } = require("pg");

const pool = new Pool({ connectionString: process.env.DATABASE_URL, ssl: process.env.NODE_ENV === "production" ? { rejectUnauthorized: false } : undefined });
const COOKIE = "rah_session";
const STATUSES = ["New inquiry", "Contacted", "Waiting for reply", "Booked", "Completed", "Lost"];
const PRIORITIES = ["Low", "Medium", "High"];
const LEAD_TYPES = ["New patient", "Returning patient"];
const METHODS = ["Phone", "Email", "Text", "In person", "Other"];
const fields = ["name", "phone", "email", "location", "referralSource", "condition", "status", "priority", "leadType", "nextFollowUp", "nextAction", "lastContactedAt", "lastContactMethod", "notes"];
function json(res, status, body) { res.status(status).setHeader("Content-Type", "application/json").send(JSON.stringify(body)); }
function cookies(req) { return Object.fromEntries(String(req.headers.cookie || "").split(/; */).filter(Boolean).map(v => { const i=v.indexOf("="); return [v.slice(0,i), decodeURIComponent(v.slice(i+1))]; })); }
function sign(value) { return crypto.createHmac("sha256", process.env.SESSION_SECRET).update(value).digest("base64url"); }
function session(req) { const value=cookies(req)[COOKIE]; if (!value) return false; const [expires,sig]=value.split("."); if (!expires || Number(expires)<Date.now()) return false; const expected=sign(expires); return sig?.length===expected.length && crypto.timingSafeEqual(Buffer.from(sig),Buffer.from(expected)); }
function verifyPassword(password) { const encoded=process.env.AUTH_PASSWORD_HASH || ""; const [algorithm,salt,hash]=encoded.split("$"); if (algorithm!=="scrypt" || !salt || !hash) return false; const actual=crypto.scryptSync(String(password),Buffer.from(salt,"base64url"),32); const expected=Buffer.from(hash,"base64url"); return actual.length===expected.length && crypto.timingSafeEqual(actual,expected); }
function cleanString(v,max=500) { return typeof v === "string" ? v.trim().slice(0,max) : ""; }
function validateLead(input) { const lead={}; fields.forEach(k=>lead[k]=cleanString(input?.[k], k==="notes"?4000:500)); const errors={}; for (const k of ["name","phone","location","condition","status","priority","leadType"]) if(!lead[k]) errors[k]="Required"; if(!/^\d{7,15}$/.test(lead.phone.replace(/\D/g,""))) errors.phone="Invalid phone"; if(lead.email&&!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(lead.email)) errors.email="Invalid email"; if(!STATUSES.includes(lead.status)) errors.status="Invalid status"; if(!PRIORITIES.includes(lead.priority)) errors.priority="Invalid priority"; if(!LEAD_TYPES.includes(lead.leadType)) errors.leadType="Invalid lead type"; if(lead.nextFollowUp&&!/^\d{4}-\d{2}-\d{2}$/.test(lead.nextFollowUp)) errors.nextFollowUp="Invalid date"; if(lead.lastContactMethod&&!METHODS.includes(lead.lastContactMethod)) errors.lastContactMethod="Invalid method"; if(lead.lastContactedAt&&Number.isNaN(Date.parse(lead.lastContactedAt))) errors.lastContactedAt="Invalid timestamp"; return {lead,errors}; }
function row(r) { return { id:r.id, createdAt:r.created_at.toISOString(), name:r.name, phone:r.phone, email:r.email||"", location:r.location, referralSource:r.referral_source||"", condition:r.condition, status:r.status, priority:r.priority, leadType:r.lead_type, nextFollowUp:r.next_follow_up?.toISOString().slice(0,10)||"", nextAction:r.next_action||"", lastContactedAt:r.last_contacted_at?.toISOString()||"", lastContactMethod:r.last_contact_method||"", bookedAt:r.booked_at?.toISOString()||"", notes:r.notes||"", activities:r.activities||[] }; }
const select = `SELECT l.*, COALESCE(json_agg(json_build_object('id',a.id,'leadId',a.lead_id,'type',a.type,'activityAt',a.activity_at,'contactMethod',a.contact_method,'note',a.note,'createdAt',a.created_at) ORDER BY a.activity_at) FILTER (WHERE a.id IS NOT NULL),'[]') activities FROM leads l LEFT JOIN activities a ON a.lead_id=l.id WHERE l.owner_id=$1 GROUP BY l.id ORDER BY l.created_at DESC`;
function csvCell(v){return `"${String(v??"").replace(/"/g,'""')}"`;}
function csv(records){const cols=[["Name","name"],["Phone","phone"],["Email","email"],["Location","location"],["Condition","condition"],["Notes","notes"],["Status","status"],["Priority","priority"],["Lead type","leadType"],["Referral source","referralSource"],["Next action","nextAction"],["Follow-up date (YYYY-MM-DD)","nextFollowUp"],["Last contacted date/time (ISO 8601)","lastContactedAt"],["Last contact method","lastContactMethod"],["Booked date/time (ISO 8601)","bookedAt"],["Created date/time (ISO 8601)","createdAt"]]; return "\uFEFF"+[cols.map(x=>x[0]),...records.map(r=>cols.map(x=>r[x[1]]))].map(x=>x.map(csvCell).join(",")).join("\n");}
module.exports = async (req,res) => { try { if(!process.env.SESSION_SECRET||!process.env.AUTH_PASSWORD_HASH||!process.env.DATABASE_URL) return json(res,503,{error:"Server is not configured"}); const route=Array.isArray(req.query?.route)?req.query.route.join("/"):req.query?.route; const path=route?`/${route}`:(req.url.split("?")[0].replace(/^\/api/,"")||"/"); if(path==="/login"&&req.method==="POST"){if(!verifyPassword(req.body?.password)) return json(res,401,{error:"Incorrect email or password"}); const expires=Date.now()+8*60*60*1000; res.setHeader("Set-Cookie",`${COOKIE}=${expires}.${sign(String(expires))}; Path=/; HttpOnly; Secure; SameSite=Strict; Max-Age=28800`); return json(res,200,{ok:true});} if(path==="/logout"&&req.method==="POST"){res.setHeader("Set-Cookie",`${COOKIE}=; Path=/; HttpOnly; Secure; SameSite=Strict; Max-Age=0`);return json(res,200,{ok:true});} if(!session(req)) return json(res,401,{error:"Authentication required"}); const owner="primary";
if(path==="/session"&&req.method==="GET") return json(res,200,{authenticated:true});
if(path==="/leads"&&req.method==="GET"){const q=await pool.query(select,[owner]);return json(res,200,{leads:q.rows.map(row)});}
if(path==="/leads"&&req.method==="POST"){const {lead,errors}=validateLead(req.body);if(Object.keys(errors).length)return json(res,400,{error:"Invalid lead",fields:errors});const id=crypto.randomUUID(),now=new Date().toISOString();await pool.query("BEGIN");try{await pool.query(`INSERT INTO leads(id,owner_id,name,phone,email,location,referral_source,condition,status,priority,lead_type,next_follow_up,next_action,last_contacted_at,last_contact_method,booked_at,notes) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,NULLIF($12,'')::date,$13,NULLIF($14,'')::timestamptz,$15,CASE WHEN $9='Booked' THEN now() END,$16)`,[id,owner,lead.name,lead.phone,lead.email,lead.location,lead.referralSource,lead.condition,lead.status,lead.priority,lead.leadType,lead.nextFollowUp,lead.nextAction,lead.lastContactedAt,lead.lastContactMethod,lead.notes]);await pool.query("INSERT INTO activities(id,lead_id,owner_id,type,activity_at) VALUES($1,$2,$3,'Lead created',$4)",[crypto.randomUUID(),id,owner,now]);await pool.query("COMMIT");}catch(e){await pool.query("ROLLBACK");throw e;}const q=await pool.query(select,[owner]);return json(res,201,{lead:q.rows.map(row).find(x=>x.id===id)});}
const match=path.match(/^\/leads\/([0-9a-f-]+)(?:\/(activity))?$/);if(match&&match[2]&&req.method==="POST"){const method=cleanString(req.body?.contactMethod), note=cleanString(req.body?.note,160),at=cleanString(req.body?.activityAt);if(!METHODS.includes(method)||Number.isNaN(Date.parse(at)))return json(res,400,{error:"Invalid activity"});const found=await pool.query("UPDATE leads SET last_contacted_at=$1,last_contact_method=$2 WHERE id=$3 AND owner_id=$4 RETURNING id",[at,method,match[1],owner]);if(!found.rowCount)return json(res,404,{error:"Lead not found"});await pool.query("INSERT INTO activities(id,lead_id,owner_id,type,activity_at,contact_method,note) VALUES($1,$2,$3,'Contacted',$4,$5,$6)",[crypto.randomUUID(),match[1],owner,at,method,note]);return json(res,201,{ok:true});}
if(match&&!match[2]&&req.method==="PUT"){const {lead,errors}=validateLead(req.body);if(Object.keys(errors).length)return json(res,400,{error:"Invalid lead",fields:errors});const q=await pool.query(`UPDATE leads SET name=$1,phone=$2,email=$3,location=$4,referral_source=$5,condition=$6,status=$7,priority=$8,lead_type=$9,next_follow_up=NULLIF($10,'')::date,next_action=$11,last_contacted_at=NULLIF($12,'')::timestamptz,last_contact_method=$13,notes=$14,booked_at=CASE WHEN $7='Booked' THEN COALESCE(booked_at,now()) ELSE booked_at END,updated_at=now() WHERE id=$15 AND owner_id=$16 RETURNING id`,[lead.name,lead.phone,lead.email,lead.location,lead.referralSource,lead.condition,lead.status,lead.priority,lead.leadType,lead.nextFollowUp,lead.nextAction,lead.lastContactedAt,lead.lastContactMethod,lead.notes,match[1],owner]);if(!q.rowCount)return json(res,404,{error:"Lead not found"});return json(res,200,{ok:true});}
if(match&&!match[2]&&req.method==="DELETE"){const q=await pool.query("DELETE FROM leads WHERE id=$1 AND owner_id=$2",[match[1],owner]);return q.rowCount?json(res,200,{ok:true}):json(res,404,{error:"Lead not found"});}
if(path==="/export"&&req.method==="GET"){const q=await pool.query(select,[owner]);res.setHeader("Content-Type","text/csv; charset=utf-8");res.setHeader("Content-Disposition",'attachment; filename="restore-at-home-leads.csv"');return res.status(200).send(csv(q.rows.map(row)));}
if(path==="/import/preview"&&req.method==="POST"){if(!Array.isArray(req.body?.leads))return json(res,400,{error:"Expected leads array"});const valid=req.body.leads.map(validateLead).filter(x=>!Object.keys(x.errors).length);return json(res,200,{total:req.body.leads.length,valid:valid.length,invalid:req.body.leads.length-valid.length});}
if(path==="/import"&&req.method==="POST"){if(!Array.isArray(req.body?.leads)||req.body.leads.length>500)return json(res,400,{error:"Expected at most 500 leads"});const checked=req.body.leads.map(validateLead);if(checked.some(x=>Object.keys(x.errors).length))return json(res,400,{error:"Every imported lead must be valid"});let count=0;for(const {lead} of checked){req.body=lead;const id=crypto.randomUUID();await pool.query(`INSERT INTO leads(id,owner_id,name,phone,email,location,referral_source,condition,status,priority,lead_type,next_follow_up,next_action,last_contacted_at,last_contact_method,notes) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,NULLIF($12,'')::date,$13,NULLIF($14,'')::timestamptz,$15,$16)`,[id,owner,lead.name,lead.phone,lead.email,lead.location,lead.referralSource,lead.condition,lead.status,lead.priority,lead.leadType,lead.nextFollowUp,lead.nextAction,lead.lastContactedAt,lead.lastContactMethod,lead.notes]);count++;}return json(res,201,{imported:count});}
return json(res,404,{error:"Not found"}); } catch(e){console.error(e);return json(res,500,{error:"Server error"});} };
module.exports.validateLead=validateLead; module.exports.verifyPassword=verifyPassword;
