const crypto = require("node:crypto");
const { Pool } = require("pg");
const auth = require("../business/auth.js");
const pool = new Pool({ connectionString: process.env.DATABASE_URL, ssl: process.env.NODE_ENV === "production" ? { rejectUnauthorized: false } : undefined });
const COOKIE="rah_session", SESSION_MS=8*60*60*1000;
const STATUSES=["New inquiry","Contacted","Waiting for reply","Booked","Completed","Lost"], PRIORITIES=["Low","Medium","High"], LEAD_TYPES=["New patient","Returning patient"], METHODS=["Phone","Email","Text","In person","Other"];
const fields=["name","phone","email","location","referralSource","condition","status","priority","leadType","nextFollowUp","nextAction","lastContactedAt","lastContactMethod","notes"];
function json(res,status,body){res.status(status).setHeader("Content-Type","application/json");res.setHeader("Cache-Control","no-store");return res.send(JSON.stringify(body));}
function cookies(req){return Object.fromEntries(String(req.headers.cookie||"").split(/; */).filter(Boolean).map(v=>{const i=v.indexOf("=");return [v.slice(0,i),decodeURIComponent(v.slice(i+1))];}));}
function tokenHash(token){return crypto.createHmac("sha256",process.env.SESSION_SECRET).update(token).digest("base64url");}
function invitationHash(code){return crypto.createHmac("sha256",process.env.INVITATION_PEPPER||process.env.SESSION_SECRET).update(String(code).trim().toUpperCase()).digest("base64url");}
function setCookie(res,token,maxAge=SESSION_MS/1000){res.setHeader("Set-Cookie",`${COOKIE}=${token}; Path=/; HttpOnly; Secure; SameSite=Strict; Max-Age=${maxAge}`);}
async function createSession(db,user,req,res){const token=crypto.randomBytes(32).toString("base64url"),expires=new Date(Date.now()+SESSION_MS);await db.query("INSERT INTO sessions(user_id,token_hash,session_version,expires_at,user_agent,ip_address) VALUES($1,$2,$3,$4,$5,$6)",[user.id,tokenHash(token),user.session_version,expires,String(req.headers["user-agent"]||"").slice(0,300),req.headers["x-forwarded-for"]?.split(",")[0]||null]);setCookie(res,token);}
async function getSession(req){const token=cookies(req)[COOKIE];if(!token)return null;const q=await pool.query(`SELECT s.id session_id,s.user_id,u.username_normalized username,u.display_name,u.role,u.status,u.session_version FROM sessions s JOIN users u ON u.id=s.user_id WHERE s.token_hash=$1 AND s.expires_at>now() AND s.session_version=u.session_version`,[tokenHash(token)]);const user=q.rows[0];if(!user||user.status!=="active")return null;await pool.query("UPDATE sessions SET last_seen_at=now() WHERE id=$1",[user.session_id]);return user;}
function cleanString(v,max=500){return typeof v==="string"?v.trim().slice(0,max):"";}
function validateLead(input){const lead={};fields.forEach(k=>lead[k]=cleanString(input?.[k],k==="notes"?4000:500));const errors={};for(const k of ["name","phone","location","condition","status","priority","leadType"])if(!lead[k])errors[k]="Required";if(!/^\d{7,15}$/.test(lead.phone.replace(/\D/g,"")))errors.phone="Invalid phone";if(lead.email&&!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(lead.email))errors.email="Invalid email";if(!STATUSES.includes(lead.status))errors.status="Invalid status";if(!PRIORITIES.includes(lead.priority))errors.priority="Invalid priority";if(!LEAD_TYPES.includes(lead.leadType))errors.leadType="Invalid lead type";if(lead.nextFollowUp&&!/^\d{4}-\d{2}-\d{2}$/.test(lead.nextFollowUp))errors.nextFollowUp="Invalid date";if(lead.lastContactMethod&&!METHODS.includes(lead.lastContactMethod))errors.lastContactMethod="Invalid method";if(lead.lastContactedAt&&Number.isNaN(Date.parse(lead.lastContactedAt)))errors.lastContactedAt="Invalid timestamp";return {lead,errors};}
function row(r){return{id:r.id,createdAt:r.created_at.toISOString(),name:r.name,phone:r.phone,email:r.email||"",location:r.location,referralSource:r.referral_source||"",condition:r.condition,status:r.status,priority:r.priority,leadType:r.lead_type,nextFollowUp:r.next_follow_up?.toISOString().slice(0,10)||"",nextAction:r.next_action||"",lastContactedAt:r.last_contacted_at?.toISOString()||"",lastContactMethod:r.last_contact_method||"",bookedAt:r.booked_at?.toISOString()||"",notes:r.notes||"",activities:r.activities||[]};}
const select=`SELECT l.*,COALESCE(json_agg(json_build_object('id',a.id,'leadId',a.lead_id,'type',a.type,'activityAt',a.activity_at,'contactMethod',a.contact_method,'note',a.note,'createdAt',a.created_at) ORDER BY a.activity_at) FILTER(WHERE a.id IS NOT NULL),'[]') activities FROM leads l LEFT JOIN activities a ON a.lead_id=l.id AND a.owner_id=$1 WHERE l.owner_id=$1 GROUP BY l.id ORDER BY l.created_at DESC`;
function csvCell(v){return `"${String(v??"").replace(/"/g,'""')}"`;} function csv(records){const cols=[["Name","name"],["Phone","phone"],["Email","email"],["Location","location"],["Condition","condition"],["Notes","notes"],["Status","status"],["Priority","priority"],["Lead type","leadType"],["Created","createdAt"]];return "\uFEFF"+[cols.map(x=>x[0]),...records.map(r=>cols.map(x=>r[x[1]]))].map(x=>x.map(csvCell).join(",")).join("\n");}
async function transaction(fn){const db=await pool.connect();try{await db.query("BEGIN");const out=await fn(db);await db.query("COMMIT");return out;}catch(e){await db.query("ROLLBACK");throw e;}finally{db.release();}}
function routeOf(req){const route=Array.isArray(req.query?.route)?req.query.route.join("/"):req.query?.route;return route?`/${route}`:(req.url.split("?")[0].replace(/^\/api/,"")||"/");}
async function register(req,res){const {normalized,valid}=auth.validateUsername(req.body?.username),display=cleanString(req.body?.displayName,100),password=req.body?.password,code=cleanString(req.body?.invitationCode,128);if(!valid||!display||display.length<2||!auth.passwordIsStrong(password)||password!==req.body?.passwordConfirmation||!code)return json(res,400,{error:"Registration details are invalid"});try{const result=await transaction(async db=>{const invitation=await db.query("SELECT id FROM registration_invitations WHERE code_hash=$1 AND consumed_at IS NULL AND revoked_at IS NULL AND expires_at>now() FOR UPDATE",[invitationHash(code)]);if(!invitation.rowCount)throw Object.assign(new Error("invalid invitation"),{public:true});const recoveryCode=auth.generateRecoveryCode();const user=await db.query("INSERT INTO users(username_normalized,display_name,password_hash,recovery_code_hash) VALUES($1,$2,$3,$4) RETURNING id,session_version",[normalized,display,auth.hashPassword(password),auth.hashRecoveryCode(recoveryCode,process.env.RECOVERY_CODE_PEPPER)]);await db.query("UPDATE registration_invitations SET consumed_at=now(),consumed_by=$1 WHERE id=$2 AND consumed_at IS NULL",[user.rows[0].id,invitation.rows[0].id]);await createSession(db,user.rows[0],req,res);return recoveryCode;});return json(res,201,{ok:true,recoveryCode:result});}catch(e){if(e.public||e.code==="23505")return json(res,400,{error:"Registration details are invalid"});throw e;}}
async function recover(req,res){const username=auth.normalizeUsername(req.body?.username).slice(0,32),code=cleanString(req.body?.recoveryCode,128),password=req.body?.newPassword;const subject=tokenHash(`${username}|${req.headers["x-forwarded-for"]||"unknown"}`);const limit=await pool.query("SELECT attempts,blocked_until,window_started_at FROM recovery_attempt_limits WHERE subject_hash=$1",[subject]);if(limit.rows[0]?.blocked_until>new Date())return json(res,400,{error:"Recovery failed"});if(!auth.passwordIsStrong(password)||!username||!code)return json(res,400,{error:"Recovery failed"});const replacement=await transaction(async db=>{const q=await db.query("SELECT * FROM users WHERE username_normalized=$1 AND status='active' FOR UPDATE",[username]);const u=q.rows[0],candidate=auth.hashRecoveryCode(code,process.env.RECOVERY_CODE_PEPPER);if(!u||!u.recovery_code_hash||!auth.safeEqualText(candidate,u.recovery_code_hash)){await db.query(`INSERT INTO recovery_attempt_limits(subject_hash,attempts,window_started_at,blocked_until) VALUES($1,1,now(),NULL) ON CONFLICT(subject_hash) DO UPDATE SET attempts=CASE WHEN recovery_attempt_limits.window_started_at<now()-interval '1 hour' THEN 1 ELSE recovery_attempt_limits.attempts+1 END,window_started_at=CASE WHEN recovery_attempt_limits.window_started_at<now()-interval '1 hour' THEN now() ELSE recovery_attempt_limits.window_started_at END,blocked_until=CASE WHEN recovery_attempt_limits.attempts>=4 THEN now()+interval '1 hour' ELSE recovery_attempt_limits.blocked_until END`,[subject]);return null;}const next=auth.generateRecoveryCode();await db.query("UPDATE users SET password_hash=$1,recovery_code_hash=$2,session_version=session_version+1,updated_at=now() WHERE id=$3",[auth.hashPassword(password),auth.hashRecoveryCode(next,process.env.RECOVERY_CODE_PEPPER),u.id]);await db.query("DELETE FROM sessions WHERE user_id=$1",[u.id]);await db.query("DELETE FROM recovery_attempt_limits WHERE subject_hash=$1",[subject]);return next;});return replacement?json(res,200,{ok:true,recoveryCode:replacement}):json(res,400,{error:"Recovery failed"});}
module.exports=async(req,res)=>{try{if(!process.env.SESSION_SECRET||!process.env.RECOVERY_CODE_PEPPER||!process.env.DATABASE_URL)return json(res,503,{error:"Server is not configured"});const path=routeOf(req);
if(path==="/register"&&req.method==="POST")return register(req,res);if(path==="/recover"&&req.method==="POST")return recover(req,res);
if(path==="/login"&&req.method==="POST"){const username=auth.normalizeUsername(req.body?.username).slice(0,32);const q=await pool.query("SELECT * FROM users WHERE username_normalized=$1",[username]);const user=q.rows[0];if(!user||user.status!=="active"||!auth.verifyPassword(req.body?.password,user.password_hash))return json(res,401,{error:"Sign-in failed"});await transaction(db=>createSession(db,user,req,res));return json(res,200,{ok:true});}
if(path==="/logout"&&req.method==="POST"){const token=cookies(req)[COOKIE];if(token)await pool.query("DELETE FROM sessions WHERE token_hash=$1",[tokenHash(token)]);setCookie(res,"",0);return json(res,200,{ok:true});}
const user=await getSession(req);if(!user)return json(res,401,{error:"Authentication required"});const owner=user.user_id;
if(path==="/session"&&req.method==="GET")return json(res,200,{authenticated:true,user:{username:user.username,displayName:user.display_name,role:user.role}});
if(path==="/security/password"&&req.method==="POST"){const q=await pool.query("SELECT password_hash FROM users WHERE id=$1",[owner]);if(!auth.verifyPassword(req.body?.currentPassword,q.rows[0].password_hash)||!auth.passwordIsStrong(req.body?.newPassword))return json(res,400,{error:"Password change failed"});await pool.query("UPDATE users SET password_hash=$1,updated_at=now() WHERE id=$2",[auth.hashPassword(req.body.newPassword),owner]);return json(res,200,{ok:true});}
if(path==="/security/recovery-code"&&req.method==="POST"){const q=await pool.query("SELECT password_hash FROM users WHERE id=$1",[owner]);if(!auth.verifyPassword(req.body?.currentPassword,q.rows[0].password_hash))return json(res,400,{error:"Recovery code regeneration failed"});const code=auth.generateRecoveryCode();await pool.query("UPDATE users SET recovery_code_hash=$1,updated_at=now() WHERE id=$2",[auth.hashRecoveryCode(code,process.env.RECOVERY_CODE_PEPPER),owner]);return json(res,200,{ok:true,recoveryCode:code});}
if(path==="/security/sessions"&&req.method==="GET"){const q=await pool.query("SELECT id,created_at,last_seen_at,expires_at,user_agent,id=$2 AS current FROM sessions WHERE user_id=$1 AND expires_at>now() ORDER BY created_at DESC",[owner,user.session_id]);return json(res,200,{sessions:q.rows});}
if(path==="/security/sessions/others"&&req.method==="DELETE"){await pool.query("DELETE FROM sessions WHERE user_id=$1 AND id<>$2",[owner,user.session_id]);return json(res,200,{ok:true});}
if(path.match(/^\/security\/sessions\/[0-9a-f-]+$/)&&req.method==="DELETE"){await pool.query("DELETE FROM sessions WHERE id=$1 AND user_id=$2",[path.split("/").pop(),owner]);return json(res,200,{ok:true});}
if(path==="/admin/invitations"&&req.method==="POST"){if(user.role!=="admin")return json(res,403,{error:"Forbidden"});const hours=Math.min(Math.max(Number(req.body?.expiresInHours)||24,1),168),code=crypto.randomBytes(18).toString("base64url");const q=await pool.query("INSERT INTO registration_invitations(code_hash,created_by,expires_at) VALUES($1,$2,now()+($3||' hours')::interval) RETURNING id,expires_at",[invitationHash(code),owner,String(hours)]);return json(res,201,{invitation:{...q.rows[0],code}});}
if(path==="/admin/invitations"&&req.method==="GET"){if(user.role!=="admin")return json(res,403,{error:"Forbidden"});const q=await pool.query("SELECT id,expires_at,consumed_at,revoked_at,created_at FROM registration_invitations ORDER BY created_at DESC");return json(res,200,{invitations:q.rows});}
if(path==="/admin/users"&&req.method==="GET"){if(user.role!=="admin")return json(res,403,{error:"Forbidden"});const q=await pool.query("SELECT id,username_normalized,display_name,role,status,created_at FROM users ORDER BY username_normalized");return json(res,200,{users:q.rows});}
if(path.match(/^\/admin\/invitations\/[0-9a-f-]+$/)&&req.method==="DELETE"){if(user.role!=="admin")return json(res,403,{error:"Forbidden"});await pool.query("UPDATE registration_invitations SET revoked_at=now() WHERE id=$1 AND consumed_at IS NULL",[path.split("/").pop()]);return json(res,200,{ok:true});}
if(path.match(/^\/admin\/users\/[0-9a-f-]+\/disable$/)&&req.method==="POST"){if(user.role!=="admin")return json(res,403,{error:"Forbidden"});const target=path.split("/")[3];await transaction(async db=>{const t=(await db.query("SELECT id,role,status FROM users WHERE id=$1 FOR UPDATE",[target])).rows[0];if(!t)throw Object.assign(new Error(),{notFound:true});if(t.id===owner&&t.role==="admin"&&t.status==="active"){const c=await db.query("SELECT count(*)::int n FROM users WHERE role='admin' AND status='active'");if(c.rows[0].n<=1)throw Object.assign(new Error(),{finalAdmin:true});}await db.query("UPDATE users SET status='disabled',session_version=session_version+1,updated_at=now() WHERE id=$1",[target]);await db.query("DELETE FROM sessions WHERE user_id=$1",[target]);});return json(res,200,{ok:true});}
if(path==="/leads"&&req.method==="GET"){const q=await pool.query(select,[owner]);return json(res,200,{leads:q.rows.map(row)});}
if(path==="/leads"&&req.method==="POST"){const {lead,errors}=validateLead(req.body);if(Object.keys(errors).length)return json(res,400,{error:"Invalid lead",fields:errors});const id=crypto.randomUUID();await transaction(async db=>{await db.query(`INSERT INTO leads(id,owner_id,name,phone,email,location,referral_source,condition,status,priority,lead_type,next_follow_up,next_action,last_contacted_at,last_contact_method,booked_at,notes) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,NULLIF($12,'')::date,$13,NULLIF($14,'')::timestamptz,$15,CASE WHEN $9='Booked' THEN now() END,$16)`,[id,owner,lead.name,lead.phone,lead.email,lead.location,lead.referralSource,lead.condition,lead.status,lead.priority,lead.leadType,lead.nextFollowUp,lead.nextAction,lead.lastContactedAt,lead.lastContactMethod,lead.notes]);await db.query("INSERT INTO activities(id,lead_id,owner_id,type) VALUES($1,$2,$3,'Lead created')",[crypto.randomUUID(),id,owner]);});const q=await pool.query(select,[owner]);return json(res,201,{lead:q.rows.map(row).find(x=>x.id===id)});}
const match=path.match(/^\/leads\/([0-9a-f-]+)(?:\/(activity))?$/);if(match&&match[2]&&req.method==="POST"){const method=cleanString(req.body?.contactMethod),note=cleanString(req.body?.note,160),at=cleanString(req.body?.activityAt);if(!METHODS.includes(method)||Number.isNaN(Date.parse(at)))return json(res,400,{error:"Invalid activity"});const found=await pool.query("UPDATE leads SET last_contacted_at=$1,last_contact_method=$2 WHERE id=$3 AND owner_id=$4 RETURNING id",[at,method,match[1],owner]);if(!found.rowCount)return json(res,404,{error:"Lead not found"});await pool.query("INSERT INTO activities(id,lead_id,owner_id,type,activity_at,contact_method,note) VALUES($1,$2,$3,'Contacted',$4,$5,$6)",[crypto.randomUUID(),match[1],owner,at,method,note]);return json(res,201,{ok:true});}
if(match&&!match[2]&&req.method==="PUT"){const {lead,errors}=validateLead(req.body);if(Object.keys(errors).length)return json(res,400,{error:"Invalid lead",fields:errors});const q=await pool.query(`UPDATE leads SET name=$1,phone=$2,email=$3,location=$4,referral_source=$5,condition=$6,status=$7,priority=$8,lead_type=$9,next_follow_up=NULLIF($10,'')::date,next_action=$11,last_contacted_at=NULLIF($12,'')::timestamptz,last_contact_method=$13,notes=$14,booked_at=CASE WHEN $7='Booked' THEN COALESCE(booked_at,now()) ELSE booked_at END,updated_at=now() WHERE id=$15 AND owner_id=$16 RETURNING id`,[lead.name,lead.phone,lead.email,lead.location,lead.referralSource,lead.condition,lead.status,lead.priority,lead.leadType,lead.nextFollowUp,lead.nextAction,lead.lastContactedAt,lead.lastContactMethod,lead.notes,match[1],owner]);return q.rowCount?json(res,200,{ok:true}):json(res,404,{error:"Lead not found"});}
if(match&&!match[2]&&req.method==="DELETE"){const q=await pool.query("DELETE FROM leads WHERE id=$1 AND owner_id=$2",[match[1],owner]);return q.rowCount?json(res,200,{ok:true}):json(res,404,{error:"Lead not found"});}
if(path==="/export"&&req.method==="GET"){const q=await pool.query(select,[owner]);res.setHeader("Content-Type","text/csv; charset=utf-8");res.setHeader("Content-Disposition",'attachment; filename="restore-at-home-leads.csv"');return res.status(200).send(csv(q.rows.map(row)));}
if(path==="/import/preview"&&req.method==="POST"){if(!Array.isArray(req.body?.leads))return json(res,400,{error:"Expected leads array"});const valid=req.body.leads.map(validateLead).filter(x=>!Object.keys(x.errors).length);return json(res,200,{total:req.body.leads.length,valid:valid.length,invalid:req.body.leads.length-valid.length});}
if(path==="/import"&&req.method==="POST"){if(!Array.isArray(req.body?.leads)||req.body.leads.length>500)return json(res,400,{error:"Expected at most 500 leads"});const checked=req.body.leads.map(validateLead);if(checked.some(x=>Object.keys(x.errors).length))return json(res,400,{error:"Every imported lead must be valid"});await transaction(async db=>{for(const {lead} of checked)await db.query(`INSERT INTO leads(owner_id,name,phone,email,location,referral_source,condition,status,priority,lead_type,next_follow_up,next_action,last_contacted_at,last_contact_method,notes) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,NULLIF($11,'')::date,$12,NULLIF($13,'')::timestamptz,$14,$15)`,[owner,lead.name,lead.phone,lead.email,lead.location,lead.referralSource,lead.condition,lead.status,lead.priority,lead.leadType,lead.nextFollowUp,lead.nextAction,lead.lastContactedAt,lead.lastContactMethod,lead.notes]);});return json(res,201,{imported:checked.length});}
return json(res,404,{error:"Not found"});}catch(e){if(e.finalAdmin)return json(res,409,{error:"The final active administrator cannot be disabled"});if(e.notFound)return json(res,404,{error:"Not found"});console.error(e);return json(res,500,{error:"Server error"});}};
module.exports.validateLead=validateLead;module.exports.auth=auth;
